---

  name: docker-push-containers-to-dockerhub-and-ecr.yaml
  
  on:
    push:
      tags:
        - "[0-9]+.[0-9]+.[0-9]+"
  
  jobs:
    docker-push-containers-to-dockerhub-and-ecr:
      permissions:
        id-token: write   # This is required for requesting the JWT
        contents: read    # This is required for actions/checkout
      uses: Senzing/build-resources/.github/workflows/docker-push-containers-to-dockerhub-and-ecr.yaml@main
      with:
        docker-image-repository: senzing/xterm
        ecr-image-repository: senzing/xterm
        image-tag: ${{ github.ref_name }}
      secrets:
        AWS_DOCKER_ACCOUNT_ID: ${{ secrets.AWS_DOCKER_ACCOUNT_ID }}
        DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
