name: docker-push-containers-to-dockerhub-and-ecr.yaml

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  attestations: write
  contents: write
  id-token: write

jobs:
  docker-push-containers-to-dockerhub-and-ecr:
    outputs:
      status: ${{ job.status }}
    runs-on: ubuntu-latest

    steps:
      - name: Build docker image and push to DockerHub
        uses: senzing-factory/github-action-docker-buildx-build@v2
        with:
          image-repository: senzing/xterm
          image-tag: ${{ github.ref_name }}
          login-to-ecr: true
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          push: true
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          role-to-assume: arn:aws:iam::${{ secrets.AWS_DOCKER_ACCOUNT_ID }}:role/github-actions-ecr-push
          sign-image: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}

  slack-notification:
    needs: [docker-push-containers-to-dockerhub-and-ecr]
    if: ${{ always() && contains(fromJSON('["failure", "cancelled"]'), needs.docker-push-containers-to-dockerhub-and-ecr.outputs.status) }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/build-failure-slack-notification.yaml@v2
    with:
      job-status: ${{ needs.docker-push-containers-to-dockerhub-and-ecr.outputs.status }}
