name: Docker build container

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker-build-container:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository name
        id: repo-basename
        run: |
          echo "repo=$(basename ${{ github.repository }})" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Build docker image
        uses: senzing-factory/github-action-docker-buildx-build@v1
        with:
          image-repository: senzing/${{ steps.repo-basename.outputs.repo }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
