name: docker-push-containers-to-dockerhub.yaml

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  docker-push-containers-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Build docker image and push to DockerHub
        uses: Senzing/github-action-docker-buildx-build@latest
        with:
          build-options: "--push"
          image-repository: senzing/xterm
          image-tag: ${{ github.ref_name }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
